[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]

name = "cardtale"
version = "0.1.0"
authors = [
    {name = "Vitor Cerqueira", email = "cerqueira.vitormanuel@gmail.com" },
]
keywords = [
    "Machine Learning",
    "Model Cards",
    "Data Science",
    "Time Series",
    "Forecasting"
]
description = "Data and Model Cards for Time Series"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
    "neuralforecast==1.7.5",
    "mlforecast==0.13.4",
    "numerize==0.12",
    "plotnine==0.13.6",
    "statsmodels==0.14.4",
    "rpy2==3.5.16",
    "weasyprint==62.3"
]

[project.urls]
"Homepage" = "https://github.com/vcerqueira/cardtale"
"Bug Tracker" = "https://github.com/vcerqueira/cardtale/issues"

[tool.hatch.build.targets.wheel]
packages = ["cardtale"]